export const mockProducts = [
    // 1. Knitwear (Kazak & Hırka)
    { slug: "merino-classic-knit", name: "Merino Classic Knit", description: "Soft and cozy merino wool sweater.", composition: "100% Merino Wool", images: [], priceCents: 39999, stock: 20, colors: ["Navy","Beige"], sizes: ["S","M","L","XL"], categorySlug: "knitwear" },
    { slug: "cashmere-v-neck", name: "Cashmere V-Neck", description: "Luxury cashmere v-neck sweater.", composition: "100% Cashmere", images: [], priceCents: 59999, stock: 15, colors: ["Grey","Black"], sizes: ["S","M","L","XL"], categorySlug: "knitwear" },
    { slug: "ribbed-crew-knit", name: "Ribbed Crew Knit", description: "Classic ribbed crew neck sweater.", composition: "70% Wool, 30% Nylon", images: [], priceCents: 34999, stock: 25, colors: ["Green","Navy"], sizes: ["S","M","L","XL"], categorySlug: "knitwear" },
    { slug: "heritage-merino-cardigan", name: "Heritage Merino Cardigan", description: "Elegant cardigan with fine stitching.", composition: "100% Merino Wool", images: [], priceCents: 44999, stock: 18, colors: ["Camel","Grey"], sizes: ["S","M","L","XL"], categorySlug: "knitwear" },
    { slug: "cotton-knit-pullover", name: "Cotton Knit Pullover", description: "Lightweight cotton pullover.", composition: "100% Cotton", images: [], priceCents: 29999, stock: 30, colors: ["Blue","White"], sizes: ["S","M","L","XL"], categorySlug: "knitwear" },
    { slug: "patterned-knit-sweater", name: "Patterned Knit Sweater", description: "Stylish patterned sweater.", composition: "80% Wool, 20% Polyester", images: [], priceCents: 42999, stock: 12, colors: ["Red","Navy"], sizes: ["S","M","L","XL"], categorySlug: "knitwear" },
    { slug: "oversized-merino-sweater", name: "Oversized Merino Sweater", description: "Comfortable oversized merino sweater.", composition: "100% Merino Wool", images: [], priceCents: 48999, stock: 10, colors: ["Beige","Olive"], sizes: ["S","M","L","XL"], categorySlug: "knitwear" },
    { slug: "fine-gauge-crew", name: "Fine Gauge Crew", description: "Elegant fine-gauge crew neck sweater.", composition: "100% Wool", images: [], priceCents: 35999, stock: 22, colors: ["Black","Grey"], sizes: ["S","M","L","XL"], categorySlug: "knitwear" },
  
    // 2. Jackets & Trench Coats
    { slug: "classic-trench-coat", name: "Classic Trench Coat", description: "Timeless trench coat with modern tailoring.", composition: "100% Cotton", images: [], priceCents: 59999, stock: 15, colors: ["Beige","Black"], sizes: ["S","M","L","XL"], categorySlug: "jackets-trench" },
    { slug: "wool-blend-coat", name: "Wool Blend Coat", description: "Warm wool-blend jacket.", composition: "70% Wool,30% Polyester", images: [], priceCents: 67999, stock: 10, colors: ["Grey","Navy"], sizes: ["S","M","L","XL"], categorySlug: "jackets-trench" },
    { slug: "double-breasted-trench", name: "Double-Breasted Trench", description: "Elegant double-breasted trench coat.", composition: "100% Cotton", images: [], priceCents: 64999, stock: 12, colors: ["Camel","Black"], sizes: ["S","M","L","XL"], categorySlug: "jackets-trench" },
    { slug: "short-cotton-jacket", name: "Short Cotton Jacket", description: "Casual short cotton jacket.", composition: "100% Cotton", images: [], priceCents: 39999, stock: 20, colors: ["Beige","Blue"], sizes: ["S","M","L","XL"], categorySlug: "jackets-trench" },
    { slug: "lightweight-raincoat", name: "Lightweight Raincoat", description: "Perfect for rainy days.", composition: "100% Polyester", images: [], priceCents: 44999, stock: 18, colors: ["Navy","Khaki"], sizes: ["S","M","L","XL"], categorySlug: "jackets-trench" },
    { slug: "biker-leather-jacket", name: "Biker Leather Jacket", description: "Stylish biker jacket.", composition: "100% Leather", images: [], priceCents: 79999, stock: 8, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "jackets-trench" },
    { slug: "hooded-cotton-jacket", name: "Hooded Cotton Jacket", description: "Casual hooded jacket.", composition: "100% Cotton", images: [], priceCents: 42999, stock: 14, colors: ["Grey","Olive"], sizes: ["S","M","L","XL"], categorySlug: "jackets-trench" },
    { slug: "peacoat-wool", name: "Peacoat Wool", description: "Classic wool peacoat.", composition: "80% Wool,20% Polyester", images: [], priceCents: 57999, stock: 10, colors: ["Navy","Black"], sizes: ["S","M","L","XL"], categorySlug: "jackets-trench" },
  
    // 3. Overcoats (Kaban)
    { slug: "camel-wool-overcoat", name: "Camel Wool Overcoat", description: "Elegant wool overcoat.", composition: "100% Wool", images: [], priceCents: 89999, stock: 10, colors: ["Camel","Black"], sizes: ["S","M","L","XL"], categorySlug: "overcoats" },
    { slug: "grey-long-coat", name: "Grey Long Coat", description: "Warm long coat for winter.", composition: "70% Wool,30% Polyester", images: [], priceCents: 85999, stock: 12, colors: ["Grey"], sizes: ["S","M","L","XL"], categorySlug: "overcoats" },
    { slug: "double-breasted-overcoat", name: "Double-Breasted Overcoat", description: "Classic formal overcoat.", composition: "100% Wool", images: [], priceCents: 92999, stock: 8, colors: ["Black","Navy"], sizes: ["S","M","L","XL"], categorySlug: "overcoats" },
    { slug: "plaid-wool-overcoat", name: "Plaid Wool Overcoat", description: "Stylish plaid overcoat.", composition: "80% Wool,20% Polyester", images: [], priceCents: 87999, stock: 9, colors: ["Grey","Brown"], sizes: ["S","M","L","XL"], categorySlug: "overcoats" },
    { slug: "single-breasted-overcoat", name: "Single Breasted Overcoat", description: "Elegant single-breasted coat.", composition: "100% Wool", images: [], priceCents: 84999, stock: 10, colors: ["Camel","Navy"], sizes: ["S","M","L","XL"], categorySlug: "overcoats" },
    { slug: "wool-blend-longcoat", name: "Wool Blend Longcoat", description: "Warm and stylish.", composition: "70% Wool,30% Polyester", images: [], priceCents: 87999, stock: 8, colors: ["Grey"], sizes: ["S","M","L","XL"], categorySlug: "overcoats" },
    { slug: "casual-overcoat", name: "Casual Overcoat", description: "Lightweight casual coat.", composition: "100% Cotton", images: [], priceCents: 69999, stock: 15, colors: ["Beige","Olive"], sizes: ["S","M","L","XL"], categorySlug: "overcoats" },
    { slug: "formal-wool-overcoat", name: "Formal Wool Overcoat", description: "Perfect for formal occasions.", composition: "100% Wool", images: [], priceCents: 89999, stock: 10, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "overcoats" },
  
    // 4. Leather Jackets (Deri Ceket)
    { slug: "classic-leather-biker", name: "Classic Leather Biker", description: "Stylish biker leather jacket.", composition: "100% Leather", images: [], priceCents: 79999, stock: 12, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "leather" },
    { slug: "brown-leather-jacket", name: "Brown Leather Jacket", description: "Casual brown leather jacket.", composition: "100% Leather", images: [], priceCents: 74999, stock: 10, colors: ["Brown"], sizes: ["S","M","L","XL"], categorySlug: "leather" },
    { slug: "suede-bomber-jacket", name: "Suede Bomber Jacket", description: "Elegant suede bomber jacket.", composition: "100% Suede", images: [], priceCents: 82999, stock: 8, colors: ["Tan"], sizes: ["S","M","L","XL"], categorySlug: "leather" },
    { slug: "black-leather-trim", name: "Black Leather Trim", description: "Leather jacket with black trims.", composition: "100% Leather", images: [], priceCents: 79999, stock: 10, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "leather" },
    { slug: "zipper-front-leather", name: "Zipper Front Leather", description: "Modern leather jacket with zipper.", composition: "100% Leather", images: [], priceCents: 81999, stock: 12, colors: ["Brown","Black"], sizes: ["S","M","L","XL"], categorySlug: "leather" },
    { slug: "biker-stylish-jacket", name: "Biker Stylish Jacket", description: "Casual biker jacket.", composition: "100% Leather", images: [], priceCents: 78999, stock: 10, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "leather" },
    { slug: "suede-classic-jacket", name: "Suede Classic Jacket", description: "Timeless suede jacket.", composition: "100% Suede", images: [], priceCents: 82999, stock: 9, colors: ["Tan"], sizes: ["S","M","L","XL"], categorySlug: "leather" },
    { slug: "faux-leather-jacket", name: "Faux Leather Jacket", description: "Eco-friendly faux leather jacket.", composition: "100% PU", images: [], priceCents: 69999, stock: 15, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "leather" },
  
    // 5. Blazers
    { slug: "navy-wool-blazer", name: "Navy Wool Blazer", description: "Classic tailored navy blazer.", composition: "100% Wool", images: [], priceCents: 74999, stock: 12, colors: ["Navy"], sizes: ["S","M","L","XL"], categorySlug: "blazers" },
    { slug: "grey-linen-blazer", name: "Grey Linen Blazer", description: "Lightweight linen blazer.", composition: "100% Linen", images: [], priceCents: 69999, stock: 15, colors: ["Grey"], sizes: ["S","M","L","XL"], categorySlug: "blazers" },
    { slug: "black-tailored-blazer", name: "Black Tailored Blazer", description: "Elegant black blazer.", composition: "70% Wool, 30% Polyester", images: [], priceCents: 79999, stock: 10, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "blazers" },
    { slug: "checked-blazer", name: "Checked Blazer", description: "Stylish checked pattern blazer.", composition: "80% Wool, 20% Polyester", images: [], priceCents: 82999, stock: 8, colors: ["Grey","Brown"], sizes: ["S","M","L","XL"], categorySlug: "blazers" },
    { slug: "beige-casual-blazer", name: "Beige Casual Blazer", description: "Smart casual blazer for all occasions.", composition: "100% Cotton", images: [], priceCents: 69999, stock: 14, colors: ["Beige"], sizes: ["S","M","L","XL"], categorySlug: "blazers" },
    { slug: "double-breasted-blazer", name: "Double Breasted Blazer", description: "Fashionable double-breasted blazer.", composition: "70% Wool,30% Polyester", images: [], priceCents: 84999, stock: 9, colors: ["Black","Navy"], sizes: ["S","M","L","XL"], categorySlug: "blazers" },
    { slug: "navy-casual-blazer", name: "Navy Casual Blazer", description: "Versatile navy blazer.", composition: "100% Cotton", images: [], priceCents: 72999, stock: 11, colors: ["Navy"], sizes: ["S","M","L","XL"], categorySlug: "blazers" },
    { slug: "patterned-wool-blazer", name: "Patterned Wool Blazer", description: "Elegant wool blazer with subtle pattern.", composition: "100% Wool", images: [], priceCents: 83999, stock: 10, colors: ["Grey","Black"], sizes: ["S","M","L","XL"], categorySlug: "blazers" },
    
    // 6. Shirts (Gömlek)
    { slug: "white-cotton-shirt", name: "White Cotton Shirt", description: "Classic white cotton shirt.", composition: "100% Cotton", images: [], priceCents: 24999, stock: 20, colors: ["White"], sizes: ["S","M","L","XL"], categorySlug: "shirts" },
    { slug: "blue-dress-shirt", name: "Blue Dress Shirt", description: "Elegant blue shirt for formal occasions.", composition: "100% Cotton", images: [], priceCents: 25999, stock: 18, colors: ["Blue"], sizes: ["S","M","L","XL"], categorySlug: "shirts" },
    { slug: "grey-slim-fit-shirt", name: "Grey Slim Fit Shirt", description: "Modern slim fit shirt.", composition: "100% Cotton", images: [], priceCents: 26999, stock: 15, colors: ["Grey"], sizes: ["S","M","L","XL"], categorySlug: "shirts" },
    { slug: "checked-casual-shirt", name: "Checked Casual Shirt", description: "Stylish checked shirt for casual wear.", composition: "100% Cotton", images: [], priceCents: 23999, stock: 22, colors: ["Red","Blue"], sizes: ["S","M","L","XL"], categorySlug: "shirts" },
    { slug: "linen-short-sleeve-shirt", name: "Linen Short Sleeve Shirt", description: "Light linen shirt for summer.", composition: "100% Linen", images: [], priceCents: 24999, stock: 20, colors: ["White","Beige"], sizes: ["S","M","L","XL"], categorySlug: "shirts" },
    { slug: "black-formal-shirt", name: "Black Formal Shirt", description: "Elegant black shirt.", composition: "100% Cotton", images: [], priceCents: 25999, stock: 16, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "shirts" },
    { slug: "denim-casual-shirt", name: "Denim Casual Shirt", description: "Trendy denim shirt.", composition: "100% Cotton", images: [], priceCents: 27999, stock: 12, colors: ["Blue"], sizes: ["S","M","L","XL"], categorySlug: "shirts" },
    { slug: "patterned-dress-shirt", name: "Patterned Dress Shirt", description: "Subtle pattern for formal style.", composition: "100% Cotton", images: [], priceCents: 28999, stock: 10, colors: ["White","Blue"], sizes: ["S","M","L","XL"], categorySlug: "shirts" },
    
    // 7. Polo Shirts
    { slug: "classic-polo-navy", name: "Classic Polo Navy", description: "Timeless navy polo shirt.", composition: "100% Cotton", images: [], priceCents: 19999, stock: 25, colors: ["Navy"], sizes: ["S","M","L","XL"], categorySlug: "polo" },
    { slug: "white-polo-shirt", name: "White Polo Shirt", description: "Clean white polo for casual wear.", composition: "100% Cotton", images: [], priceCents: 19999, stock: 20, colors: ["White"], sizes: ["S","M","L","XL"], categorySlug: "polo" },
    { slug: "black-slim-polo", name: "Black Slim Polo", description: "Modern slim fit polo.", composition: "100% Cotton", images: [], priceCents: 20999, stock: 18, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "polo" },
    { slug: "green-classic-polo", name: "Green Classic Polo", description: "Comfortable green polo shirt.", composition: "100% Cotton", images: [], priceCents: 19999, stock: 22, colors: ["Green"], sizes: ["S","M","L","XL"], categorySlug: "polo" },
    { slug: "red-sport-polo", name: "Red Sport Polo", description: "Sporty red polo for active days.", composition: "100% Cotton", images: [], priceCents: 20999, stock: 15, colors: ["Red"], sizes: ["S","M","L","XL"], categorySlug: "polo" },
    { slug: "beige-classic-polo", name: "Beige Classic Polo", description: "Elegant beige polo.", composition: "100% Cotton", images: [], priceCents: 19999, stock: 20, colors: ["Beige"], sizes: ["S","M","L","XL"], categorySlug: "polo" },
    { slug: "navy-sport-polo", name: "Navy Sport Polo", description: "Active navy polo.", composition: "100% Cotton", images: [], priceCents: 20999, stock: 15, colors: ["Navy"], sizes: ["S","M","L","XL"], categorySlug: "polo" },
    { slug: "white-classic-polo", name: "White Classic Polo", description: "Classic white polo shirt.", composition: "100% Cotton", images: [], priceCents: 19999, stock: 18, colors: ["White"], sizes: ["S","M","L","XL"], categorySlug: "polo" },
    
        // 8. T-Shirts
    { slug: "classic-white-tshirt", name: "Classic White T-Shirt", description: "Soft cotton white t-shirt.", composition: "100% Cotton", images: [], priceCents: 14999, stock: 30, colors: ["White"], sizes: ["S","M","L","XL"], categorySlug: "tshirts" },
    { slug: "black-crew-tshirt", name: "Black Crew T-Shirt", description: "Essential black t-shirt.", composition: "100% Cotton", images: [], priceCents: 14999, stock: 25, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "tshirts" },
    { slug: "grey-vneck-tshirt", name: "Grey V-Neck T-Shirt", description: "Comfortable grey v-neck t-shirt.", composition: "100% Cotton", images: [], priceCents: 15999, stock: 20, colors: ["Grey"], sizes: ["S","M","L","XL"], categorySlug: "tshirts" },
    { slug: "navy-graphic-tshirt", name: "Navy Graphic T-Shirt", description: "Trendy navy t-shirt with subtle graphic.", composition: "100% Cotton", images: [], priceCents: 16999, stock: 18, colors: ["Navy"], sizes: ["S","M","L","XL"], categorySlug: "tshirts" },
    { slug: "olive-casual-tshirt", name: "Olive Casual T-Shirt", description: "Casual olive t-shirt.", composition: "100% Cotton", images: [], priceCents: 15999, stock: 22, colors: ["Olive"], sizes: ["S","M","L","XL"], categorySlug: "tshirts" },
    { slug: "beige-crew-tshirt", name: "Beige Crew T-Shirt", description: "Soft beige t-shirt.", composition: "100% Cotton", images: [], priceCents: 14999, stock: 25, colors: ["Beige"], sizes: ["S","M","L","XL"], categorySlug: "tshirts" },
    { slug: "white-vintage-tshirt", name: "White Vintage T-Shirt", description: "White t-shirt with vintage style.", composition: "100% Cotton", images: [], priceCents: 15999, stock: 20, colors: ["White"], sizes: ["S","M","L","XL"], categorySlug: "tshirts" },
    { slug: "black-graphic-tshirt", name: "Black Graphic T-Shirt", description: "Black t-shirt with minimalist graphic.", composition: "100% Cotton", images: [], priceCents: 16999, stock: 18, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "tshirts" },
    
    // 9. Pants (Pantolon)
    { slug: "navy-chinos", name: "Navy Chinos", description: "Classic navy chinos.", composition: "100% Cotton", images: [], priceCents: 39999, stock: 20, colors: ["Navy"], sizes: ["S","M","L","XL"], categorySlug: "pants" },
    { slug: "grey-wool-trousers", name: "Grey Wool Trousers", description: "Elegant wool trousers.", composition: "100% Wool", images: [], priceCents: 49999, stock: 15, colors: ["Grey"], sizes: ["S","M","L","XL"], categorySlug: "pants" },
    { slug: "black-slim-pants", name: "Black Slim Pants", description: "Modern slim fit pants.", composition: "70% Wool,30% Polyester", images: [], priceCents: 45999, stock: 18, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "pants" },
    { slug: "khaki-casual-pants", name: "Khaki Casual Pants", description: "Lightweight casual pants.", composition: "100% Cotton", images: [], priceCents: 39999, stock: 22, colors: ["Khaki"], sizes: ["S","M","L","XL"], categorySlug: "pants" },
    { slug: "blue-denim-trousers", name: "Blue Denim Trousers", description: "Casual denim trousers.", composition: "100% Cotton", images: [], priceCents: 42999, stock: 20, colors: ["Blue"], sizes: ["S","M","L","XL"], categorySlug: "pants" },
    { slug: "beige-linen-pants", name: "Beige Linen Pants", description: "Breathable linen pants.", composition: "100% Linen", images: [], priceCents: 41999, stock: 18, colors: ["Beige"], sizes: ["S","M","L","XL"], categorySlug: "pants" },
    { slug: "black-formal-pants", name: "Black Formal Pants", description: "Perfect for office or events.", composition: "70% Wool,30% Polyester", images: [], priceCents: 47999, stock: 16, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "pants" },
    { slug: "olive-casual-chinos", name: "Olive Casual Chinos", description: "Comfortable olive chinos.", composition: "100% Cotton", images: [], priceCents: 39999, stock: 20, colors: ["Olive"], sizes: ["S","M","L","XL"], categorySlug: "pants" },
    
    // 10. Jeans
    { slug: "blue-slim-jeans", name: "Blue Slim Jeans", description: "Classic slim fit jeans.", composition: "100% Cotton", images: [], priceCents: 39999, stock: 25, colors: ["Blue"], sizes: ["S","M","L","XL"], categorySlug: "jeans" },
    { slug: "black-straight-jeans", name: "Black Straight Jeans", description: "Straight fit black jeans.", composition: "100% Cotton", images: [], priceCents: 39999, stock: 20, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "jeans" },
    { slug: "grey-slim-jeans", name: "Grey Slim Jeans", description: "Modern grey slim jeans.", composition: "100% Cotton", images: [], priceCents: 40999, stock: 18, colors: ["Grey"], sizes: ["S","M","L","XL"], categorySlug: "jeans" },
    { slug: "dark-blue-straight", name: "Dark Blue Straight", description: "Casual dark blue straight jeans.", composition: "100% Cotton", images: [], priceCents: 39999, stock: 22, colors: ["Dark Blue"], sizes: ["S","M","L","XL"], categorySlug: "jeans" },
    { slug: "black-ripped-jeans", name: "Black Ripped Jeans", description: "Trendy black ripped jeans.", composition: "100% Cotton", images: [], priceCents: 41999, stock: 15, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "jeans" },
    { slug: "light-blue-jeans", name: "Light Blue Jeans", description: "Casual light blue jeans.", composition: "100% Cotton", images: [], priceCents: 39999, stock: 20, colors: ["Light Blue"], sizes: ["S","M","L","XL"], categorySlug: "jeans" },
    { slug: "grey-distressed-jeans", name: "Grey Distressed Jeans", description: "Modern grey distressed jeans.", composition: "100% Cotton", images: [], priceCents: 41999, stock: 16, colors: ["Grey"], sizes: ["S","M","L","XL"], categorySlug: "jeans" },
    { slug: "navy-slim-jeans", name: "Navy Slim Jeans", description: "Smart casual navy jeans.", composition: "100% Cotton", images: [], priceCents: 40999, stock: 18, colors: ["Navy"], sizes: ["S","M","L","XL"], categorySlug: "jeans" },
    
    // 11. Suits (Takım Elbise)
    { slug: "navy-classic-suit", name: "Navy Classic Suit", description: "Timeless navy suit, perfect for formal occasions.", composition: "100% Wool", images: [], priceCents: 199999, stock: 10, colors: ["Navy"], sizes: ["48","50","52","54"], categorySlug: "suits" },
    { slug: "grey-slim-fit-suit", name: "Grey Slim Fit Suit", description: "Modern grey slim fit suit.", composition: "100% Wool", images: [], priceCents: 209999, stock: 8, colors: ["Grey"], sizes: ["48","50","52","54"], categorySlug: "suits" },
    { slug: "black-formal-suit", name: "Black Formal Suit", description: "Elegant black suit for special events.", composition: "100% Wool", images: [], priceCents: 219999, stock: 6, colors: ["Black"], sizes: ["48","50","52","54"], categorySlug: "suits" },
    { slug: "charcoal-classic-suit", name: "Charcoal Classic Suit", description: "Charcoal suit with classic cut.", composition: "100% Wool", images: [], priceCents: 199999, stock: 9, colors: ["Charcoal"], sizes: ["48","50","52","54"], categorySlug: "suits" },
    { slug: "blue-striped-suit", name: "Blue Striped Suit", description: "Blue suit with subtle stripes.", composition: "100% Wool", images: [], priceCents: 209999, stock: 7, colors: ["Blue"], sizes: ["48","50","52","54"], categorySlug: "suits" },
    { slug: "brown-linen-suit", name: "Brown Linen Suit", description: "Lightweight brown linen suit for summer.", composition: "100% Linen", images: [], priceCents: 189999, stock: 8, colors: ["Brown"], sizes: ["48","50","52","54"], categorySlug: "suits" },
    { slug: "black-pinstripe-suit", name: "Black Pinstripe Suit", description: "Classic black suit with pinstripes.", composition: "100% Wool", images: [], priceCents: 219999, stock: 5, colors: ["Black"], sizes: ["48","50","52","54"], categorySlug: "suits" },
    { slug: "navy-slim-suit", name: "Navy Slim Suit", description: "Slim fit navy suit for modern style.", composition: "100% Wool", images: [], priceCents: 209999, stock: 6, colors: ["Navy"], sizes: ["48","50","52","54"], categorySlug: "suits" },
    
    // 12. Fragrances (Parfüm)
    { slug: "alverro-cedarwood", name: "Alverro Cedarwood", description: "Woody fragrance for men.", composition: "Alcohol, Cedarwood, Musk, Amber", images: [], priceCents: 12999, stock: 50, colors: [], sizes: [], categorySlug: "fragrances" },
    { slug: "alverro-citrus-fresh", name: "Alverro Citrus Fresh", description: "Refreshing citrus scent.", composition: "Alcohol, Lemon, Bergamot, Orange", images: [], priceCents: 11999, stock: 40, colors: [], sizes: [], categorySlug: "fragrances" },
    { slug: "alverro-amber-night", name: "Alverro Amber Night", description: "Warm amber fragrance.", composition: "Alcohol, Amber, Vanilla, Sandalwood", images: [], priceCents: 13999, stock: 30, colors: [], sizes: [], categorySlug: "fragrances" },
    { slug: "alverro-rose-blossom", name: "Alverro Rose Blossom", description: "Floral perfume for women.", composition: "Alcohol, Rose, Jasmine, Musk", images: [], priceCents: 12999, stock: 45, colors: [], sizes: [], categorySlug: "fragrances" },
    { slug: "alverro-ocean-breeze", name: "Alverro Ocean Breeze", description: "Fresh aquatic fragrance.", composition: "Alcohol, Sea Notes, Musk, Citrus", images: [], priceCents: 11999, stock: 40, colors: [], sizes: [], categorySlug: "fragrances" },
    { slug: "alverro-vanilla-essence", name: "Alverro Vanilla Essence", description: "Sweet vanilla fragrance.", composition: "Alcohol, Vanilla, Tonka Bean, Sandalwood", images: [], priceCents: 12999, stock: 35, colors: [], sizes: [], categorySlug: "fragrances" },
    { slug: "alverro-forest-mystic", name: "Alverro Forest Mystic", description: "Earthy forest fragrance.", composition: "Alcohol, Pine, Cedar, Vetiver", images: [], priceCents: 13999, stock: 30, colors: [], sizes: [], categorySlug: "fragrances" },
    { slug: "alverro-spice-aroma", name: "Alverro Spice Aroma", description: "Warm and spicy scent.", composition: "Alcohol, Cinnamon, Clove, Sandalwood", images: [], priceCents: 12999, stock: 35, colors: [], sizes: [], categorySlug: "fragrances" },
    
    // 13. Underwear (İç Giyim)
    { slug: "cotton-briefs", name: "Cotton Briefs", description: "Comfortable cotton briefs.", composition: "100% Cotton", images: [], priceCents: 7999, stock: 50, colors: ["White","Black","Grey"], sizes: ["S","M","L","XL"], categorySlug: "underwear" },
    { slug: "modal-boxers", name: "Modal Boxers", description: "Soft modal fabric boxers.", composition: "95% Modal,5% Elastane", images: [], priceCents: 8999, stock: 45, colors: ["Black","Blue","Grey"], sizes: ["S","M","L","XL"], categorySlug: "underwear" },
    { slug: "seamless-briefs", name: "Seamless Briefs", description: "Smooth seamless fit.", composition: "90% Cotton,10% Elastane", images: [], priceCents: 8499, stock: 40, colors: ["White","Black"], sizes: ["S","M","L","XL"], categorySlug: "underwear" },
    { slug: "classic-boxers", name: "Classic Boxers", description: "Classic cotton boxers.", composition: "100% Cotton", images: [], priceCents: 7999, stock: 50, colors: ["White","Blue"], sizes: ["S","M","L","XL"], categorySlug: "underwear" },
    { slug: "microfiber-briefs", name: "Microfiber Briefs", description: "Soft microfiber fabric.", composition: "90% Polyamide,10% Elastane", images: [], priceCents: 8999, stock: 35, colors: ["Black","Grey"], sizes: ["S","M","L","XL"], categorySlug: "underwear" },
    { slug: "sport-boxers", name: "Sport Boxers", description: "Activewear cotton boxers.", composition: "95% Cotton,5% Elastane", images: [], priceCents: 8499, stock: 40, colors: ["Grey","Black"], sizes: ["S","M","L","XL"], categorySlug: "underwear" },
    { slug: "linen-briefs", name: "Linen Briefs", description: "Breathable linen fabric briefs.", composition: "100% Linen", images: [], priceCents: 8999, stock: 30, colors: ["Beige"], sizes: ["S","M","L","XL"], categorySlug: "underwear" },
    { slug: "black-comfort-briefs", name: "Black Comfort Briefs", description: "Comfortable everyday briefs.", composition: "100% Cotton", images: [], priceCents: 7999, stock: 50, colors: ["Black"], sizes: ["S","M","L","XL"], categorySlug: "underwear" },

  ];
  